joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 400

joint_effort_group_controller:
   type: effort_controllers/JointGroupEffortController
   joints:
      - LH_HAA
      - LH_HFE
      - LH_KFE   
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE
