joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

joint_effort_group_controller:
   type: effort_controllers/JointGroupEffortController
   joints:
      - LH_HAA
      - LH_HFE
      - LH_KFE   
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE

LF_HAA_controller:
    type: effort_controllers/JointPositionController
    joint: LF_HAA
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

LF_HFE_controller:
    type: effort_controllers/JointPositionController
    joint: LF_HFE
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

LF_KFE_controller:
    type: effort_controllers/JointPositionController
    joint: LF_KFE
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

RF_HAA_controller:
    type: effort_controllers/JointPositionController
    joint: RF_HAA
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

RF_HFE_controller:
    type: effort_controllers/JointPositionController
    joint: RF_HFE
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

RF_KFE_controller:
    type: effort_controllers/JointPositionController
    joint: RF_KFE
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

LH_HAA_controller:
    type: effort_controllers/JointPositionController
    joint: LH_HAA
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

LH_HFE_controller:
    type: effort_controllers/JointPositionController
    joint: LH_HFE
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

LH_KFE_controller:
    type: effort_controllers/JointPositionController
    joint: LH_KFE
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

RH_HAA_controller:
    type: effort_controllers/JointPositionController
    joint: RH_HAA
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

RH_HFE_controller:
    type: effort_controllers/JointPositionController
    joint: RH_HFE
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}

RH_KFE_controller:
    type: effort_controllers/JointPositionController
    joint: RH_KFE
    pid: {p: 150.0, i: 10.0, d: 15.0, i_clamp_min: -10000000, i_clamp_max: 10000000}
